# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ebf07e2a36df9e2d94ca946f3333427d5707fc15602799198e04dca9bbaaf58f2da8c69c9e8c7c3ccb9613d1957d51a1188492e182f32a991186fa3a142a3d3

test:
  secret_key_base: 91407b54ab9bbde7dc93b5c392e9419e528df7821834114ae82d04d6cc2c09a618110d7a07716c14fbe58ba0aebfce2d64aa7cff6005fab8cca92f6df45a5866

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
